### ISSUE TITLE
`pip install` fails on platforms without binary wheels

### ISSUE THREAD

**Issue by AgentConDier** [decathorpe/mitmproxy_wireguard#18]
I'm running mitmdump inside [Termux](https://github.com/Termux/Termux-App). While trying to update to the latest version, the mitmproxy-wireguard wheel failed to build locally:
<pre><span color="#00AA00">~</span> <span color="#FFFFFF">$</span> pip install -U --upgrade-strategy eager mitmproxy
Requirement already satisfied: mitmproxy in /data/data/com.termux/files/usr/lib/python3.10/site-packages (8.1.1)
Collecting mitmproxy
  Using cached mitmproxy-9.0.0-py3-none-any.whl (1.6 MB)
Requirement already satisfied: wsproto&lt;1.3,&gt;=1.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (1.1.0)
Collecting wsproto&lt;1.3,&gt;=1.0
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: urwid&lt;2.2,&gt;=2.1.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (2.1.2)
Requirement already satisfied: pyperclip&lt;1.9,&gt;=1.6.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (1.8.2)
Collecting pyOpenSSL&lt;22.2,&gt;=22.1
  Using cached pyOpenSSL-22.1.0-py3-none-any.whl (57 kB)
Requirement already satisfied: msgpack&lt;1.1.0,&gt;=1.0.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (1.0.4)
Requirement already satisfied: asgiref&lt;3.6,&gt;=3.2.10 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (3.5.2)
Requirement already satisfied: flask&lt;2.3,&gt;=1.1.1 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (2.1.2)
Collecting flask&lt;2.3,&gt;=1.1.1
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Requirement already satisfied: hyperframe&lt;7,&gt;=6.0 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (6.0.1)
Requirement already satisfied: protobuf&lt;5,&gt;=3.14 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (4.21.2)
Collecting protobuf&lt;5,&gt;=3.14
  Using cached protobuf-4.21.9-py3-none-any.whl (291 kB)
Requirement already satisfied: pyparsing&lt;3.1,&gt;=2.4.2 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (3.0.9)
Requirement already satisfied: ruamel.yaml&lt;0.18,&gt;=0.16 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (0.17.21)
Requirement already satisfied: sortedcontainers&lt;2.5,&gt;=2.3 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (2.4.0)
Requirement already satisfied: passlib&lt;1.8,&gt;=1.6.5 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (1.7.4)
Requirement already satisfied: zstandard&lt;0.19,&gt;=0.11 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (0.18.0)
Collecting cryptography&lt;38.1,&gt;=38.0
  Using cached cryptography-38.0.1.tar.gz (599 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: h11&lt;0.15,&gt;=0.11 in /data/data/com.termux/files/usr/lib/python3.10/site-packages (from mitmproxy) (0.12.0)
Collecting h11&lt;0.15,&gt;=0.11
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     <span color="#87AF5F">━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</span> <span color="#00AA00">58.3/58.3 kB</span> <span color="#AA0000">852.4 kB/s</span> eta <span color="#00AAAA">0:00:00</span>
Collecting mitmproxy-wireguard&lt;0.2,&gt;=0.1.6
  Using cached mitmproxy_wireguard-0.1.14.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  <span color="#FF5555"><b>error</b></span>: <b>subprocess-exited-with-error</b>
  
  <span color="#AA0000">×</span> <span color="#00AA00">Preparing metadata </span><span color="#55FF55"><b>(</b></span><span color="#00AA00">pyproject.toml</span><span color="#55FF55"><b>)</b></span> did not run successfully.
  <span color="#AA0000">│</span> exit code: <span color="#55FFFF"><b>1</b></span>
  <span color="#AA0000">╰─&gt;</span> <span color="#AA0000">[12 lines of output]</span>
  <span color="#AA0000">   </span> 💥 maturin failed
  <span color="#AA0000">   </span>   Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  <span color="#AA0000">   </span>   Caused by: `cargo metadata` exited with an error: error: failed to load manifest for workspace member `/data/data/com.termux/files/usr/tmp/pip-install-fyxt3ct_/mitmproxy-wireguard_05d31e8eb7024923b70ca8f0f700dfe5/test-client`
  <span color="#AA0000">   </span> 
  <span color="#AA0000">   </span> Caused by:
  <span color="#AA0000">   </span>   failed to read `/data/data/com.termux/files/usr/tmp/pip-install-fyxt3ct_/mitmproxy-wireguard_05d31e8eb7024923b70ca8f0f700dfe5/test-client/Cargo.toml`
  <span color="#AA0000">   </span> 
  <span color="#AA0000">   </span> Caused by:
  <span color="#AA0000">   </span>   No such file or directory (os error 2)
  <span color="#AA0000">   </span> Error running maturin: Command &apos;[&apos;maturin&apos;, &apos;pep517&apos;, &apos;write-dist-info&apos;, &apos;--metadata-directory&apos;, &apos;/data/data/com.termux/files/usr/tmp/pip-modern-metadata-_vzn0zuw&apos;, &apos;--interpreter&apos;, &apos;/data/data/com.termux/files/usr/bin/python3&apos;]&apos; returned non-zero exit status 1.
  <span color="#AA0000">   </span> Checking for Rust toolchain....
  <span color="#AA0000">   </span> Running `maturin pep517 write-dist-info --metadata-directory /data/data/com.termux/files/usr/tmp/pip-modern-metadata-_vzn0zuw --interpreter /data/data/com.termux/files/usr/bin/python3`
  <span color="#AA0000">   </span> <span color="#AA0000">[end of output]</span>
  
  <span color="#FF55FF"><b>note</b></span>: This error originates from a subprocess, and is likely not a problem with pip.
<span color="#FF5555"><b>error</b></span>: <b>metadata-generation-failed</b>

<span color="#AA0000">×</span> Encountered error while generating package metadata.
<span color="#AA0000">╰─&gt;</span> See above for output.

<span color="#FF55FF"><b>note</b></span>: This is an issue with the package mentioned above, not pip.
<span color="#55FFFF"><b>hint</b></span>: See above for details.

<b>[</b><span color="#0000AA">notice</span><b>]</b> A new release of pip available: <span color="#AA0000">22.2.2</span> -&gt; <span color="#00AA00">22.3</span>
<b>[</b><span color="#0000AA">notice</span><b>]</b> To update, run: <span color="#00AA00">pip install --upgrade pip</span>
</pre>
My best guess would be that this happens because https://github.com/decathorpe/mitmproxy_wireguard/blob/bbd32cd9b431dcec3e9486b88208f15d55cd1325/Cargo.toml#L65
is included in the PyPi source archive, but the test client code isn't.

Software versions:
```
~ $ rustc -Vv
rustc 1.64.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-linux-android
release: 1.64.0
LLVM version: 15.0.1
~ $ python --version
Python 3.10.8
~ $ maturin --version
maturin 0.13.7
```

**Comment by AgentConDier** [comment]
I can confirm that after removing the test-client line from Cargo.toml, pip is able to install from the source archive just fine.

**Comment by decathorpe** [comment]
Oh dear, this looks like a bug in maturin (the tool we use for building / publishing sdist and binary wheels). The `[workspace]` table should either be dropped, or the `test-client` directory should be included ... I'll try to figure out how to work around this problem.

**Comment by decathorpe** [comment]
I've tagged and published a new version that should contain a workaround for this problem:

- https://github.com/decathorpe/mitmproxy_wireguard/releases/tag/0.1.15
- https://pypi.org/project/mitmproxy-wireguard/0.1.15/

It would be great if you could confirm that this actually fixes the problem for you, as well.

**Comment by AgentConDier** [comment]
Yes, it's building successfully now for me. Thanks for the quick fix!
