### ISSUE TITLE
update GitHub actions to avoid actions running on deprecated NodeJS 12

### ISSUE THREAD

**Issue by decathorpe** [decathorpe/mitmproxy_wireguard#19]
It looks like the unmaintained `actions-rs` actions will be affected by the deprecation of old NodeJS 12 based actions:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

The easiest solution is probably to run `cargo` commands directly, even if doing that means we'll lose commit and PR annotations :(

---

Looks like we're also using old versions of the `actions/checkout` action, but updating from `actions/checkout@v2` `actions/checkout@v3` should solve the problem there.

The same problem also seems to apply to `actions/upload-artifact`, `actions/setup-python`, and `actions/download-artifact` actions ... not sure if we can just bump to new versions, as for some actions, the way to pass them arguments has changed.

**Comment by mhils** [comment]
FWIW they are just switching to Node 16, so things will for the most part just continue to work. Back to topic, `actions/setup-python`, `actions/upload-artifact` and `actions/download-artifact` can be safely bumped without further changes, I've done the same for mitmproxy itself a few days ago. For `actions-rs` I'll leave it up to you if you prefer the warnings or direct cargo invocations. :)
