### ISSUE TITLE
Is this still needed for mitmproxy?

### ISSUE THREAD

**Issue by kpcyrd** [decathorpe/mitmproxy_wireguard#27]
Hello!

Arch Linux currently packages python-mitmproxy-wireguard and python-mitmproxy-rs, but it seems only python-mitmproxy-rs is still needed by mitmproxy, and the other one (from this repository) has been replaced.

Is this correct? If so I would remove the -wireguard package :)

Thank you!

**Comment by mhils** [comment]
Yes, that's correct. mitmproxy-wireguard has been extended and renamed to mitmproxy-rs. Thanks! :)

**Comment by kpcyrd** [comment]
Thanks for clarifying! :)
